### ISSUE TITLE
API is not secured

### ISSUE THREAD

**Issue by linuxchr** [noel-friedrich/terminal#21]
You can access the API from web and so you can send command to upload a very high highscore with your name:
https://www.noel-friedrich.de/terminal//api/upload_highscore.php?game=tetris&name=Christian&score=42424242&

**Comment by linuxchr** [comment]
Deutsch:

Wie wäre es mit einer Lösung bei der die API nur vom Server aus abrufbar ist?
Dies wäre nicht Perfekt, aber es schwieriger machen.


Christian

**Comment by linuxchr** [comment]
Am zum Upload des Scores sendet Server einen Symetrischen Schlüssel mit dem Score verschlüsselt wird und beim Server dann Entschlüssechlt. Dies ist aber nicht Ideal, wenn man den Schlüssel abgreift und dann einen Neuen Score einsetzt.

**Comment by noel-friedrich** [comment]
Die Spiele, wie alle Befehle, laufen ausschließlich auf dem Client; der Server hat kein (das soll auch so bleiben) Wissen darüber, wenn Befehle ausgeführt werden. Jede Form von "Security" die man an der Schnittstelle implementieren will, ist keine "Security", denn mein JS Code (der inherent auf dem Client läuft) muss nach einem Spiel immer den Score hochladen können. Wenn der Befehl das kann, kann das jeder mit Lust auch tun. Auch Ansätze mit (a)symmetrischen Verschlüsselungen scheitern am gleichen Problem. 

Meiner Meinung nach wäre die einzig mögliche Security die Spiele auf dem Server laufen/überprüfen zu lassen, sodass z.B. der Client am Ende eines Spiels alle Spiel-Inputs gesendet werden und der Server nachvollziehen kann, ob das Spiel so wirklich passiert ist. Bei Spielen mit Zufall (z.b. `number-guess`) würden die Zahlen dass natürlich irgendwie aus einer nachvollziehbaren Quelle gezogen werden (seeded random wie mit sha und der zeit als input). Das ist allerdings echt viel Aufwand! Zu viel für mich :)

Letztlich kann man Cheating bei den Highscores nicht verhindern, nur schwieriger machen. Bisher sind die Highscores noch unproblematisch und das neue Confirm-System ist nicht perfekt, aber verhindert, dass irgendwer zu viel Spaß dran hat. Und bis zum Zeitpunkt an dem das zu viel Arbeit wird, benutze ich den [Ostrich algorithm](https://en.wikipedia.org/wiki/Ostrich_algorithm).

Sorry für den Aufsatz
- Noel (liebe Grüße an den alten Herr Lange!)
